### ISSUE TITLE
Integrate NZIC site

### ISSUE THREAD

**Issue by akampjes** [NZOI/website#14]

**Comment by andrewcchen** [comment]
HAHAHA CSS

**Comment by akampjes** [comment]
Interested in helping?
I think Greg did some work on it the NZIC site. I could find it for you?

**Comment by andrewcchen** [comment]
Now that the feature is implemented in #15, perhaps @ronalchn can set up redirects on the [old site](nzic.nzoi.org.nz).

**Comment by akampjes** [comment]
Good idea, @ronalchn could you make nzic.nzoi.org.nz redirect to http://www.nzoi.org.nz/nzic/ ?
